language: python
python:
  - "2.7"
before-install:
  - pip install pika paho-mqtt avro kafka-python hl7apy
services:
  - rabbitmq
before-script:
  - rabbitmq-plugins enable rabbitmq_mqtt
install:
  - python setup.py install
script:
  - nosetests tests clay
branches:
  only:
    - develop