language: python
python:
  - "2.7"
before_install:
  - pip install pika paho-mqtt avro kafka-python hl7apy
services:
  - rabbitmq
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_mqtt
  - sudo service rabbitmq-server restart
install:
  - python setup.py install
script:
  - nosetests tests clay
branches:
  only:
    - develop